// TODO: add validator to check params
#[derive(Debug)]
pub enum Type {
    CHAR(usize),
    VARCHAR(usize),
    BINARY(usize),
    VARBINARY(usize),
    TINYBLOB,
    TINYTEXT,
    TEXT(usize),
    BLOB(usize),
    MEDIUMTEXT,
    MEDIUMBLOB,
    LONGTEXT,
    LONGBLOB,
    ENUM { values: Vec<String> },
    SET { values: Vec<String> },
    BIT(usize),
    TINYINT(usize),
    BOOL,
    SMALLINT(usize),
    MEDIUMINT(usize),
    INT(usize),
    BIGINT(usize),
    FLOAT(usize, usize),
    DOUBLE(usize, usize),
    DECIMAL(usize, usize),
    DATE,
    DATETIME,
    TIMESTAMP,
    TIME,
    YEAR,
}
